import { Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Nav";

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} antialiased bg-[#000214] text-white`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
